// <auto-generated />
using System;
using MarketPulse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketPulse.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719095110_AddMarketPrices")]
    partial class AddMarketPrices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketPulse.Api.Models.FinancialInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Currency = "USD",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Name = "Apple Inc.",
                            Ticker = "AAPL"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Currency = "USD",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Name = "Microsoft Corporation",
                            Ticker = "MSFT"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Currency = "USD",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Name = "NVIDIA Corporation",
                            Ticker = "NVDA"
                        });
                });

            modelBuilder.Entity("MarketPulse.Api.Models.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FinancialInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FinancialInstrumentId");

                    b.ToTable("MarketPrices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("568d3499-2337-4dfa-9edc-cdf202d3f901"),
                            ClosePrice = 212.43m,
                            FinancialInstrumentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TimestampUtc = new DateTime(2026, 7, 16, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("568d3499-2337-4dfa-9edc-cdf202d3f902"),
                            ClosePrice = 214.10m,
                            FinancialInstrumentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TimestampUtc = new DateTime(2026, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("568d3499-2337-4dfa-9edc-cdf202d3f903"),
                            ClosePrice = 215.87m,
                            FinancialInstrumentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TimestampUtc = new DateTime(2026, 7, 18, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ebfcf39f-b825-46cf-bb43-3bb687a52341"),
                            ClosePrice = 501.22m,
                            FinancialInstrumentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TimestampUtc = new DateTime(2026, 7, 16, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ebfcf39f-b825-46cf-bb43-3bb687a52342"),
                            ClosePrice = 503.15m,
                            FinancialInstrumentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TimestampUtc = new DateTime(2026, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ebfcf39f-b825-46cf-bb43-3bb687a52343"),
                            ClosePrice = 505.61m,
                            FinancialInstrumentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TimestampUtc = new DateTime(2026, 7, 18, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3039f58b-557f-4a25-a3df-c2eebdb554a1"),
                            ClosePrice = 173.45m,
                            FinancialInstrumentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TimestampUtc = new DateTime(2026, 7, 16, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3039f58b-557f-4a25-a3df-c2eebdb554a2"),
                            ClosePrice = 176.92m,
                            FinancialInstrumentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TimestampUtc = new DateTime(2026, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("3039f58b-557f-4a25-a3df-c2eebdb554a3"),
                            ClosePrice = 179.84m,
                            FinancialInstrumentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TimestampUtc = new DateTime(2026, 7, 18, 21, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("MarketPulse.Api.Models.MarketPrice", b =>
                {
                    b.HasOne("MarketPulse.Api.Models.FinancialInstrument", "FinancialInstrument")
                        .WithMany("Prices")
                        .HasForeignKey("FinancialInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialInstrument");
                });

            modelBuilder.Entity("MarketPulse.Api.Models.FinancialInstrument", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
